mapnik:
        build: osm-mapnik
        links:
                - db:postgres-osm
        ports:
                - "8081:80"
mongodb:
        build: osm-mongodb
        volumes:
                - /srv/geopicardie/volumes/mongo:/data/db
mapproxy:
        build: osm-mapproxy
        links:
                - mapnik:styles-wms
                - mongodb
        ports:
                - "8080:80"
db:
        build: osm-db
        volumes:
                - /srv/geopicardie/volumes/postgres:/var/lib/postgresql
                - /srv/geopicardie/volumes/osm-data:/srv/data
        environment:
                - OSM_PBF=http://download.geofabrik.de/europe/france-latest.osm.pbf
