mapnik:
        build: osm-mapnik
        links:
                - db:postgres-osm
        ports:
                - "8081:80"
mongodb:
        build: osm-mongodb
        ports:
                - "27017:27017"
        volumes:
                - /srv/geopicardie/volumes/mongo:/data/db
        environment:
                - REPL_SET=mongoosm
mapproxy:
        build: osm-mapproxy
        links:
                - mapnik:styles-wms
                - mongodb
        ports:
                - "8080:80"
        extends:
                file: docker-compose-local.yml
                service: mapproxy
db:
        build: osm-db
        volumes:
                - /srv/geopicardie/volumes/postgres:/var/lib/postgresql
                - /srv/geopicardie/volumes/osm-data:/srv/data
        environment:
                - OSM_PBF=http://download.geofabrik.de/europe/france-latest.osm.pbf
